copyright = "© LencoDigitexer"
defaultContentLanguage = "ru"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "ru"
timeZone = "Europe/Moscow"
timeout = "120s"
title = "Галерея"

[params]
  defaultTheme = "dark"
  description = "Добро пожаловать в личную галерею Евсеенко Ильи (LencoDigitexer). Здесь собраны уютные и вдохновляющие кадры природы, путешествий и повседневности. Исследуйте мир через мои глаза."
  title = "Моя галерея"
  [params.author]
    email = "user@example.com"
    name = "Your Name"
  [params.socialIcons]
    #facebook = "https://www.facebook.com/"
    #instagram = "https://www.instagram.com/protivogaser"
    github = "https://github.com/LencoDigitexer/photo"
    #youtube = "https://www.youtube.com/"
    #email = "mailto:user@example.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/nicokaiser/hugo-theme-gallery/"
    weight = 3

[services]
  [services.rss]
    limit = 100
